---
all: 
    hosts:
      server:
        ansible_host: 127.0.0.1
        ansible_port: 2208
        ansible_private_key_file: /root/OTUS/Kazay/VPN/.vagrant/machines/server/virtualbox/private_key
      client:
          ansible_host: 127.0.0.1
          ansible_port: 2209
          ansible_private_key_file: /root/OTUS/Kazay/VPN/.vagrant/machines/client/virtualbox/private_key
